### ISSUE TITLE
Missing declaration

### ISSUE THREAD

**Issue by UBX-FAE-ALEL** [u-blox/mbed-examples-odin-w2-mbed-3#2] opened 2018-07-31 14:30 UTC
C:/MBED/mbed-examples-odin-w2/udp-time-client-wifi/source/main.cpp: In function 'void app_start(int, char**)':
C:/MBED/mbed-examples-odin-w2/udp-time-client-wifi/source/main.cpp:369:17: error: 'cbWLAN_StartParameters' has no member named 'disable80211d'
     startParams.disable80211d = FALSE; // The driver must always support this feature
                 ^
ninja: build stopped: subcommand failed.
error: command ['ninja'] failed
warning: There were also errors installing and resolving dependencies, which may have caused the build failure: see above, or run `yotta install` for details.

==>>> file declaration is corrupted

**Comment by asifrizwanubx** [comment] 2018-07-31 14:42
disable80211d is no more supported. This example requires changes according to new API.

**Comment by arnaudlelannicubloxFAE** [comment] 2018-07-31 14:50
is it the same root cause than the non blocking errors I get when I want to compile:

(workspace) C:\MBED\mbed-examples-odin-w2\udp-time-client-wifi>yotta build
error: ublox-odin-w2-drivers does not meet specification ^1.0.0 required by udp-time-client-wifi
error: ublox-odin-w2-lwip-adapt does not meet specification ^1.0.0 required by udp-time-client-wifi

**Comment by asifrizwanubx** [comment] 2018-08-10 07:28
It is due to outdated documentation. We will update the documentation soon.

**Comment by AmmadRehmat** [comment] 2019-02-07 11:00
@UBX-FAE-ALEL has your issue been resolved? I would like to close this ticket in that case

**Comment by jkb1372** [comment] 2019-02-07 11:09
Thanks for contacting me.

The issue is obsolete and can be closed.

Best regards,
John Beattie

--
john.beattie@accenture.com<mailto:john.beattie@accenture.com>    +447554402015

**Closed** 2019-02-07 11:25 UTC
